# 포트 설정
server:
  port: 8090

# mysql 연결
spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  file:
    upload-dir: C:\superProfile



logging:
  level:
    org.hibernate.type: trace
    com.app: debug


cloud:
  aws:
    region:
      static: ap-northeast-2  # AWS 기본 리전을 설정
    stack:
      auto: false
    s3:
      bucket: ${S3_BUCKET}
      access-key: ${S3_ACCESS_KEY}
      secret-key: ${S3_SECRET_KEY}