# 포트 설정
server:
  port: 8080

# mysql 연결
spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  file:
    upload-dir: C:\superProfile



logging:
  level:
    org.hibernate.type: trace
    com.app: debug
