# 포트 설정
server:
  port: 8080

# mysql 연결
spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/supercoding?serverTimezone=Asia/Seoul
    username: root
    password: 12341234
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  file:
    upload-dir: C:\superProfile
  jpa:
    hibernate:
      ddl-auto: update # 스키마 자동 생성
    show-sql: true # SQL 퀴리 출력
    properties:
      hibernate:
        format_sql: true # SQL pretty print



logging:
  level:
    org.hibernate.type: trace
    com.app: debug

cloud:
  aws:
    region:
      static: ap-northeast-2  # AWS 기본 리전을 설정
    stack:
      auto: false
    s3:
      bucket: supershyshop
      access-key: AKIAUN4O5LS25F7EHF57
      secret-key: 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